apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: mynodeapp
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: sabarigirishpb/nodeapp
        ports:
        - containerPort: 9000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: mynodeapp
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 9000
    nodePort: 31111
